package Viroverse::Model::ViroDB;

use strict;
use warnings;
use base 'Catalyst::Model::DBIC::Schema';

require ViroDB;
__PACKAGE__->config(
    schema_class => 'ViroDB',
    connect_info => ViroDB->default_connection_info,
    traits       => ['QueryLog::AdoptPlack'],
    show_missing_ql_warning => 0,
);

=head1 NAME

Viroverse::Model::ViroDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Viroverse> and L<ViroDB>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<ViroDB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.61

=head1 AUTHOR

Thomas Sibley

=cut

1;
