#!/bin/bash
home=$( dirname "$0" )/..
var="$home/var"
pidfile="$var/run/server-starter.pid"
statusfile="$var/run/server-starter.status"
logfile="$var/log/server.log"

[[ -d "$var/run" ]] || mkdir -p "$var/run"
[[ -d "$var/log" ]] || mkdir -p "$var/log"

cd "$home" || exit 1

if test -s "$pidfile" && kill -0 "$(cat "$pidfile")" 2>/dev/null; then
    echo -n "Re-starting server... "
    start_server \
        --restart \
        --pid-file="$pidfile" \
        --status-file="$statusfile" \
        && echo "done" || echo "FAILED ($?)"
else
    echo -n "Starting server... "
    start_server \
        --port=localhost:8080 \
        --pid-file="$pidfile" \
        --status-file="$statusfile" \
        --interval=10 \
        -- \
        plackup -s Starlet -E "${PLACK_ENV:-deployment}" \
            -e 'enable_if { $_[0]->{REMOTE_ADDR} eq "127.0.0.1" }
                    SetEnvFromHeader => REMOTE_USER => "X-Forwarded-REMOTE-USER";
                enable "ReverseProxy";' \
            --max-workers=10 \
            --timeout=300 \
            app.psgi \
        >>"$logfile" 2>&1 &
    ret=$?
    [[ $ret == 0 ]] && echo "done" || echo "FAILED ($ret)"
    echo "Logging to $logfile"
fi
