#!/bin/bash
home=$(dirname "$( dirname "$0" )")
pidfile=$home/var/run/server-starter.pid

cd "$home" || exit 1

if [[ -s $pidfile ]]; then
    echo -n "Stopping server... "
    xargs kill < "$pidfile" \
    && echo "done" || echo "FAILED ($?)"
else
    echo "No server running (no pid file: $pidfile)"
fi
