#!/usr/bin/env perl
use strict;
use warnings;
use 5.018;

use Getopt::Long;
use FindBin '$RealBin';
use lib "$RealBin/../lib";

require Viroverse::Config;

die "Can't figure out dbname attribute from DSN '" . Viroverse::Config->conf{dsn} . "'"
    unless my ($dbname) = Viroverse::Config->conf{dsn} =~ /dbname=([^;]+)/;

GetOptions("no-drop" => \(my $no_drop));

my $testdb = "${dbname}_test";

say "Creating copy of database $dbname as $testdb";
my $start = time;

{
    use autodie ':all';
    sub run(@) {
        say "  + ", join " ", @_;
        system @_;
    }
    run "dropdb", $testdb unless $no_drop;
    run "createdb", $testdb, "-O", "vverse_admin", "-T", $dbname;
}

say sprintf "Completed in %0.1f minutes", (time - $start) / 60;

